### ISSUE TITLE
mypyで型アノテーションのチェックを行う

### ISSUE THREAD

**Issue by kexi** [chiba-data/python-project-template#2]
# 設定例
```yml:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
```

# 参考
https://zenn.dev/yiskw713/articles/3c3b4022f3e3f22d276d

**Comment by kexi** [comment]
```toml:
[tool.mypy]
python_version = "3.10"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
```
